name: Build and Deploy MkDocs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js for Mermaid CLI
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-pdf-export-plugin
        npm install -g @mermaid-js/mermaid-cli

    - name: Generate Mermaid diagrams
      run: |
        mkdir -p docs/img/svg
        for file in docs/img/diagrams/*.mmd; do
          mmdc -i "$file" -o "docs/img/svg/$(basename "${file%.mmd}.svg")" --no-sandbox
        done

    - name: Build MkDocs site
      run: mkdocs build

    - name: Upload built site as artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: site/
