site_name: OpenCMMC Stack
site_description: A Practical FOSS Implementation Guide for CMMC v2 Level 2 Readiness
site_author: Kell Engineering
site_url: https://docs.kellengineering.com

repo_name: kellengineering/open-cmmc-stack
repo_url: https://github.com/mtkell/open-cmmc-stack

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - toc.integrate
  palette:
    primary: blue grey
    accent: deep purple

nav:
  - Home: README.md
  - Preface: docs/00_preface/index.md
  - Introduction to CMMC v2: docs/01_cmmc_intro/index.md
  - Reference Architecture: docs/02_reference_architecture/index.md
  - Provisioning Infrastructure: docs/03_provisioning/index.md
  - Securing the Host OS: docs/04_os_hardening/index.md
  - Identity & Access Management: docs/05_identity_access/index.md
  - Secure File Sharing: docs/06_file_storage/index.md
  - Secure Email: docs/07_email/index.md
  - Logging & Monitoring: docs/08_logging_monitoring/index.md
  - Container Runtime: docs/09_container_runtime/index.md
  - Backup & Recovery: docs/10_backup_recovery/index.md
  - Policies & Procedures: docs/11_policies_procedures/index.md
  - Assessment & Readiness: docs/12_assessment_readiness/index.md
  - Infrastructure Architecture & System Interconnection: docs/13_architecture/index.md
  - Deployment Guide:
    - Overview: docs/14_deployment_guide/index.md
    - Phase 0- Planning & Scope: docs/14_deployment_guide/01_planning.md
    - Phase 1- Terraform Provisioning: docs/14_deployment_guide/02_terraform_provisioning.md
    - Phase 2- OS Hardening with Ansible: docs/14_deployment_guide/03_ansible_hardening.md
    - Phase 3- Podman Service Deployment: docs/14_deployment_guide/04_podman_services.md
    - Phase 3a - Nextcloud-AIO Deployment: docs/14_deployment_guide/phase04-files.md
    - Phase 4- Identity, Certs, and Access Control: docs/14_deployment_guide/05_identity_cert_mgmt.md
    - Phase 5- Client Device Registration: docs/14_deployment_guide/06_client_registration.md
    - Phase 6- Logging, SIEM, and Alerting: docs/14_deployment_guide/07_logging_monitoring.md
    - Phase 7- Validation and Reporting: docs/14_deployment_guide/08_validation_reporting.md
  - Security Operations (SecOps): docs/15_secops_sops/index.md
  - Automation & CI/CD: docs/16_automation_cicd/index.md
  - Compliance Artifacts: docs/17_compliance_artifacts/index.md
  - SSP Templates: docs/18_ssp_templates/index.md
  - Data Flow & Trust Boundaries: docs/19_data_flow_mapping/index.md
  - Performance & Cost Planning: docs/20_scaling_cost/index.md
  - Appendix A: docs/99_appendix_a_acronyms.md
  - Appendix B: docs/99_appendix_b_resources.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list

plugins:
  - search
  - pdf-export:
      combined: true
      media_type: print
