site_name: OpenCMMC Stack
site_description: A Practical FOSS Implementation Guide for CMMC v2 Level 2 Readiness
site_author: Kell Engineering
site_url: https://docs.kellengineering.com

repo_name: kellengineering/open-cmmc-stack
repo_url: https://github.com/mtkell/open-cmmc-stack

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - toc.integrate
  palette:
    primary: blue grey
    accent: deep purple

nav:
  - Home: README.md
  - Preface: 00_preface/index.md
  - Introduction to CMMC v2: 01_cmmc_intro/index.md
  - Reference Architecture: 02_reference_architecture/index.md
  - Provisioning Infrastructure: 03_provisioning/index.md
  - Securing the Host OS: 04_os_hardening/index.md
  - Identity & Access Management: 05_identity_access/index.md
  - Secure File Sharing: 06_file_storage/index.md
  - Secure Email: 07_email/index.md
  - Logging & Monitoring: 08_logging_monitoring/index.md
  - Container Runtime: 09_container_runtime/index.md
  - Backup & Recovery: 10_backup_recovery/index.md
  - Policies & Procedures: 11_policies_procedures/index.md
  - Assessment & Readiness: 12_assessment_readiness/index.md
  - Infrastructure Architecture & System Interconnection: 13_architecture/index.md
  - Deployment Guide:
    - Overview: 14_deployment_guide/index.md
    - Phase 0- Planning & Scope: 14_deployment_guide/01_planning.md
    - Phase 1- Terraform Provisioning: 14_deployment_guide/02_terraform_provisioning.md
    - Phase 2- OS Hardening with Ansible: 14_deployment_guide/03_ansible_hardening.md
    - Phase 3- Podman Service Deployment: 14_deployment_guide/04_podman_services.md
    - Phase 3a - Nextcloud-AIO Deployment: 14_deployment_guide/phase04-files.md
    - Phase 4- Identity, Certs, and Access Control: 14_deployment_guide/05_identity_cert_mgmt.md
    - Phase 5- Client Device Registration: 14_deployment_guide/06_client_registration.md
    - Phase 6- Logging, SIEM, and Alerting: 14_deployment_guide/07_logging_monitoring.md
    - Phase 7- Validation and Reporting: 14_deployment_guide/08_validation_reporting.md
  - Appendix A: 99_appendix_a_acronyms.md
  - Appendix B: 99_appendix_b_references.md


markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list

plugins:
  - search
  - pdf-export:
      combined: true
      media_type: print